<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>kube-pilot</artifactId>
        <groupId>com.kube.pilot</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>pilot-extend</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>pilot-monitor-admin</module>
        <module>pilot-snailjob-server</module>
    </modules>

</project>
