<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.kube.pilot</groupId>
        <artifactId>pilot-modules</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>pilot-demo</artifactId>

    <description>
        demo模块
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-mail</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-idempotent</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-log</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-excel</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-security</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-ratelimiter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-translation</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-sensitive</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-encrypt</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-tenant</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kube.pilot</groupId>
            <artifactId>pilot-common-websocket</artifactId>
        </dependency>

    </dependencies>

</project>
